eureka:
  instance:
    # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: subject
  application:
    name: lab-4-subject

words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: lab-4-verb

words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-4-article

words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-4-adjective

words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: lab-4-noun

words: boat,book,vote,seat,backpack,partition,groundhog


---
spring:
  profiles: cold-noun
  application:
    name: lab-4-noun

words: icicle,refrigerator,blizzard,snowball
