spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/streamlesswaveson/udemy-microservices-krueger
          search-paths: config-data
        native:
          search-locations: file:///${user.home}/PROJECTS/udemy-microservices-krueger/config-data
server:
  port: 8888